version: "3"

services:
  redis:
    image: redis:5.0.3-alpine
    container_name: redis
    hostname: redis
    command: redis-server --requirepass S3cr3t
    restart: always
    volumes:
      - ./.docker/volumes/redis:/data
    ports:
      - 6379:6379
    networks:
      - backend

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    hostname: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379:4:S3cr3t
      # - HTTP_USER=turbo
      # - HTTP_PASSWORD=S3cr3t
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - backend

networks:
  backend:
